server:
  port: 9082
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: true
    
spring:
  application:
    name: social-media-cloud-gateway